### ISSUE TITLE
kubernetes resource should be eventually consistent-- not working for vpc subnet case

### ISSUE THREAD

**Issue by prtkdave** [upbound/provider-aws#1020] opened 2023-12-13 12:45 UTC
### What environment did it happen in?

* Crossplane Version: 1.13.1
* Provider Version: 0.46
* Kubernetes Version:   1.27.1
* Kubernetes Distribution:  baremetal

**Comment by turkenf** [comment] 2024-01-16 11:33
I am closing this because the necessary/sufficient information was not provided for us to understand and reproduce the issue. If the issue recurs in provider version `0.47.1`, do not hesitate to reopen it by providing the necessary information to reproduce it.

**Closed by turkenf** 2024-01-16 11:33 UTC
Labels: bug, community, needs:triage
