### ISSUE TITLE
AWS rds replicated Instance has conflicting fields upon creation complete

### ISSUE THREAD

**Issue by rmarcus1** [upbound/provider-aws#930] opened 2023-10-21 13:16 UTC
### What happened :

When provisioning a replicated rds instance on AWS , username (which is being added by lateInit) conflicts with replicate_source_db:

```
 Type     Reason                           Age                From                                               Message
  ----     ------                           ----               ----                                               -------
  Normal   CreatedExternalResource          28m                managed/rds.aws.upbound.io/v1beta1, kind=instance  Successfully requested creation of external resource
  Warning  CannotInitializeManagedResource  28m                managed/rds.aws.upbound.io/v1beta1, kind=instance  Operation cannot be fulfilled on instances.rds.aws.upbound.io "rds-mysql": the object has been modified; please apply your changes to the latest version and try again
  Warning  CannotObserveExternalResource    68s                managed/rds.aws.upbound.io/v1beta1, kind=instance  cannot run refresh: refresh failed:
  Warning  CannotObserveExternalResource    26s (x6 over 62s)  managed/rds.aws.upbound.io/v1beta1, kind=instance  cannot run refresh: refresh failed: Conflicting configuration arguments: "username": conflicts with replicate_source_db
```

### How can we reproduce it?
Tested on  [xpkg.upbound.io/upbound/provider-aws-rds:v0.38.0](http://xpkg.upbound.io/upbound/provider-aws-rds:v0.38.0) [xpkg.upbound.io/upbound/provider-family-aws:v0.42.0](http://xpkg.upbound.io/upbound/provider-family-aws:v0.42.0)

```
apiVersion: rds.aws.upbound.io/v1beta1
 kind: Instance
 metadata:
 annotations:
   meta.upbound.io/example-id: rds/v1beta1/instance
 labels:
   testing.upbound.io/example-name: example-dbinstance
 name: rds-mysql
 spec:
   providerConfigRef:
     name: aws-provider-config
   forProvider:
     allocatedStorage: 20
     autoGeneratePassword: true
     autoMinorVersionUpgrade: true
     backupRetentionPeriod: 14
     caCertIdentifier: rds-ca-xxxxxxx
     backupWindow: 09:46-10:16
     engine: mysql
     engineVersion: "8.0.33"
     instanceClass: db.m5d.large
     dbSubnetGroupName: rds-subnetgroup
     vpcSecurityGroupIds:
       - "sg-xxxxxxxxxx"
     maintenanceWindow: Mon:00:00-Mon:03:00
     replicateSourceDb: "arn:aws:rds:us-west-2:1111111111111:db:rds-src-helm"
     kmsKeyId: "arn:aws:kms:us-west-2:11111111:alias/aws/rds22"
     passwordSecretRef:
       key: password
       name: password
       namespace: crossplane
     publiclyAccessible: true
     region: us-west-2
     skipFinalSnapshot: true
     storageEncrypted: true
     storageType: gp2
```

### What environment did it happen in?

* Crossplane Version: crossplane-1.13.2                      	1.13.2
* Provider Version:  xpkg.upbound.io/upbound/provider-aws-rds:v0.38.0
* Kubernetes Version: "v1.27.4-eks-2d98532" 
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3
* Kubernetes Distribution:  EKS

**Comment by rmarcus1** [comment] 2023-11-01 12:32
any update on this ?

**Comment by dudubis** [comment] 2023-11-08 08:14
Facing the same issue when provisioning replication. provider-aws-rds:v0.38.0 and EKS 1.28

**Comment by adizalmanovich** [comment] 2023-11-08 11:08
getting same error: cannot run refresh: refresh failed: Conflicting configuration arguments: "username": conflicts with replicate_source_db

**Comment by turkenf** [comment] 2023-11-20 11:25
I'm closing the issue because it's a duplicate of this: https://github.com/upbound/provider-aws/issues/723

**Closed by turkenf** 2023-11-20 11:25 UTC
Labels: bug, community, is:triaged

**Comment by turkenf** [comment] 2023-11-20 11:53
Hi folks,

I am writing here to keep you informed, can you let me know if [this](https://github.com/upbound/provider-aws/pull/725#issuecomment-1818899552) worked for you?
