### ISSUE TITLE
Resource SYNCED status becomes False after a while

### ISSUE THREAD

**Issue by project-administrator** [upbound/provider-aws#706] opened 2023-05-19 07:12 UTC
### What happened?
I created a bunch of *Record.route53.aws.upbound.io/v1beta1* resources (as part of the composition). Here is the resource spec:
```yaml
  spec:
    forProvider:
      name: abcdef.our.domain.
      records:
      - ns-1222.awsdns-24.org
      - ns-1776.awsdns-30.co.uk
      - ns-446.awsdns-55.com
      - ns-663.awsdns-18.net
      region: eu-west-2
      ttl: 300
      type: NS
      zoneId: Z17ABCDEFGHIJKL
```
(the `spec.forProvider.records` value is coming as a patch from another managed resource -- *Zone.route53.aws.upbound.io/v1beta1*).

Initially, resources get `READY: True` and `SYNCED: True`, but after a few hours the resource status becomes `READY: True` and `SYNCED: False` (maybe after day, maybe after the provider-aws and crossplane controller pods are restarted?). 
The `kubectl describe` shows these events for the resource:
```
  Warning  CannotObserveExternalResource  4m41s (x859 over 15h)  managed/route53.aws.upbound.io/v1beta1, kind=record  cannot run plan: plan failed: Instance cannot be destroyed: Resource aws_route53_record.sample-domaincert-fjgch has lifecycle.prevent_destroy set, but the plan calls for this resource to be destroyed. To avoid this error and continue with the plan, either disable lifecycle.prevent_destroy or reduce the scope of the plan using the -target flag.
```

At this point it tries to delete the resource, and I can't really get the reason behind this. I'm not able to determine which fields changed, why would it attempt to recreate the resource after few hours? ... Does it have anything to do with the order of the items in the `spec.forProvider.records` field? ..

The created managed resource (Route53 record) stays created and works OK in this state. But once we have dozen of such resources created, it becomes a bit of the problem because `provider-aws` starts to exhaust the AWS API limits:
```
time="2023-05-17T16:47:40Z" level=error msg="failed to list resource records sets for zone /hostedzone/Z07ABCDEFGHIJKLMN: Throttling: Rate exceeded\n\tstatus code: 400, request id: 70576bdd-ddcf-40fc-9671-e174039f578c"
```

### How can we reproduce it?

1. Create the *Record.route53.aws.upbound.io/v1beta1* resource, for example by using the below Composition.
2. Check the created resource `READY: True` and `SYNCED: True`
3. Wait for few hours or a day (maybe also try to restart the provider and crossplane controller pods).
4. Check that resource becomes `READY: True` and `SYNCED: False` after a while -- this should not happen

The XRD that we are using:
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: domaincert.our.domain.com
spec:
  group: our.domain.com
  names:
    kind: DomainCert
    plural: domaincert
  versions:
  - name: v1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  region:
                    type: string
                  UID:
                    type: string
                  parentZoneID:
                    type: string
                    description: Set the parent DNS zone ID
                    default: Z1ABCDEFGHIJKL
                required:
                - region
                - UID
            required:
            - parameters
          status:
            type: object
            properties:
              zoneID:
                description: Created DNS Zone ID
                type: string
              nameServers:
                description: List of NS servers assigned to the hosted zone
                type: array
                items:
                  type: string
              domainValidationOptions:
                type: array
                items:
                  type: object
                  properties:
                    domainName:
                      type: string
                    resourceRecordName:
                      type: string
                    resourceRecordType:
                      type: string
                    resourceRecordValue:
                      type: string
              certificateARN:
                description: ACM Certificate ARN
                type: string
```
The Composition:
```yaml
# Creates these resources:
# - Route53 DNS Zone
# - NS records for the newly created DNS zone in the parent zone
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: domaincert
  labels:
    crossplane.io/xrd: domaincert.our.domain.com
spec:
  writeConnectionSecretsToNamespace: operators
  compositeTypeRef:
    apiVersion: our.domain.com/v1
    kind: DomainCert
  resources:
  - name: zone
    base:
      apiVersion: route53.aws.upbound.io/v1beta1
      kind: Zone
      spec:
        forProvider:
          description: 'Managed by Crossplane'
        providerConfigRef:
          name: 'aws-provider-upbound'
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.UID
      toFieldPath: spec.forProvider.name
      policy:
        fromFieldPath: Required
      transforms:
        - type: string
          string:
            type: Regexp
            regexp: 
              match: "^.{0,6}" # grab only first 6 characters of the UID
        - type: string
          string:
            type: Format
            fmt: "%s.our.domain.com."
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: metadata.labels.hostedzone
      policy:
        fromFieldPath: Required
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.region
      toFieldPath: spec.forProvider.region
      policy:
        fromFieldPath: Required
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.nameServers
      toFieldPath: status.nameServers
      policy:
        fromFieldPath: Required
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.id
      toFieldPath: status.zoneID
      policy:
        fromFieldPath: Required
  - name: ns-records
    base:
      apiVersion: route53.aws.upbound.io/v1beta1
      kind: Record
      spec:
        forProvider:
          ttl: 300
          type: NS
          description: 'Managed by Crossplane'
        providerConfigRef:
          name: 'aws-provider-upbound'
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.UID
      toFieldPath: spec.forProvider.name
      transforms:
        - type: string
          string:
            type: Regexp
            regexp: 
              match: "^.{0,6}" # grab only first 6 characters of the UID
        - type: string
          string:
            type: Format
            fmt: "%s.our.domain.com."
      policy:
        fromFieldPath: Required
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.parentZoneID
      toFieldPath: spec.forProvider.zoneId
      policy:
        fromFieldPath: Required
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.region
      toFieldPath: spec.forProvider.region
      policy:
        fromFieldPath: Required
    - type: FromCompositeFieldPath
      fromFieldPath: status.nameServers
      toFieldPath: spec.forProvider.records
      policy:
        fromFieldPath: Required
```
The claim for this composition:
```yaml
apiVersion: our.domain.com/v1
kind: DomainCert
metadata:
  name: sample-domaincert
spec:
  parameters:
    region: eu-west-2
    UID: abcdef-4ee6-4afe-b455-fce52ad77af0
```

### What environment did it happen in?

* Crossplane Version: v1.12.1
* Provider Version: v0.35.0
* Kubernetes Version: v1.26.4
* Kubernetes Distribution: EKS

**Comment by svscheg** [comment] 2023-05-31 11:23
Can't reproduce issue waiting 24hours, restarted docker with next example:

```
apiVersion: route53.aws.upbound.io/v1beta1
kind: Record
metadata:
  name: example
spec:
  forProvider:
    name: abcdef.our.domain.
    region: us-west-1
    records:
    - "dev.upbound.io"
    - "dev2.upbound.io"
    - "dev3.upbound.io"
    ttl: 5
    type: NS
    zoneIdRef:
      name: example
---
apiVersion: route53.aws.upbound.io/v1beta1
kind: Zone
metadata:
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: mycompany.test
    region: us-west-1
```
Need try to restart provider-aws and crossplane controller pods cc @dverveiko could you please try it when will have time?

**Comment by project-administrator** [comment] 2023-06-02 15:53
Yes, I understand that the steps to reproduce are not reliable for triggering this issue. 
Restarting the crossplane-controller and provider-aws pods is not enough to reproduce this issue. 
The only thing I can think of is that the order of the elements returned by the AWS API from the Zone.route53.aws.upbound.io managed resource field status.atProvider.nameServers becomes different after a while. And I guess this might trigger the provider to re-create the Record.route53.aws.upbound.io managed resource..

**Comment by project-administrator** [comment] 2023-06-12 10:46
Update: I cannot reproduce this issue atm. 
I was able to work around it by using the `resourcerecordsets.route53.aws.crossplane.io` instead of the `records.route53.aws.upbound.io`, so maybe it's not worth spending time for this issue.

**Comment by turkenf** [comment] 2023-07-04 10:15
Hi @project-administrator,

Thank you for raising this issue, if you still cannot reproduce this issue and it's not blocking for you, feel free to close it.

**Closed** 2023-07-04 15:07 UTC
Labels: bug, community, needs:triage

**Comment by magic-madrigal** [comment] 2025-05-16 03:14
I'm currently experiencing this issue. 

version: `xpkg.upbound.io/upbound/provider-aws-route53:v1`

I have 10 records that it's maintaining, and it seems to be checking every second. So now Route53 is throttling all requests, impacting our ability to use the UI.

It doens't look like there is a poll interval for the resource, but I feel this would be the best solution.
