### ISSUE TITLE
v0.44.0 - `Cluster` `eks.aws.upbound.io` unable to select `subnetIds`

### ISSUE THREAD

**Issue by haarchri** [upbound/provider-aws#975] opened 2023-11-18 14:50 UTC
### What happened?

```
kubectl describe cluster.eks.aws.upbound.io/platform-ref-aws-cnoe-nm9pn-9l46l 
Name:         platform-ref-aws-cnoe-nm9pn-9l46l
Namespace:    
Labels:       crossplane.io/claim-name=platform-ref-aws-cnoe
              crossplane.io/claim-namespace=default
              crossplane.io/composite=platform-ref-aws-cnoe-nm9pn
Annotations:  crossplane.io/composition-resource-name: kubernetesCluster
              crossplane.io/external-name: platform-ref-aws-cnoe-nm9pn-9l46l
              upjet.upbound.io/test: true
API Version:  eks.aws.upbound.io/v1beta1
Kind:         Cluster
Metadata:
  Creation Timestamp:  2023-11-18T14:36:14Z
  Generate Name:       platform-ref-aws-cnoe-nm9pn-
  Generation:          718
  Owner References:
    API Version:           aws.platform.upbound.io/v1alpha1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  XEKS
    Name:                  platform-ref-aws-cnoe-nm9pn-wfzr7
    UID:                   50e377c8-d74d-4829-9184-048993a0f249
  Resource Version:        9953
  UID:                     7f8bc536-e65c-4697-8a98-ba5321503dc9
Spec:
  Deletion Policy:  Delete
  For Provider:
    Region:    us-west-2
    Role Arn:  arn:aws:iam::609897127049:role/platform-ref-aws-cnoe-nm9pn-5l8kf
    Role Arn Ref:
      Name:  platform-ref-aws-cnoe-nm9pn-5l8kf
    Role Arn Selector:
      Match Controller Ref:  true
      Match Labels:
        Role:  controlplane
    Tags:
      Crossplane - Kind:            cluster.eks.aws.upbound.io
      Crossplane - Name:            platform-ref-aws-cnoe-nm9pn-9l46l
      Crossplane - Providerconfig:  default
    Version:                        1.27
    Vpc Config:
      Endpoint Private Access:  true
      Endpoint Public Access:   true
      Subnet Id Selector:
        Match Labels:
          Access:                                       public
          networks.aws.platform.upbound.io/network-id:  platform-ref-aws-cnoe
  Init Provider:
  Management Policies:
    *
  Provider Config Ref:
    Name:  default
Status:
  At Provider:
  Conditions:
    Last Transition Time:  2023-11-18T14:36:23Z
    Message:               cannot resolve references: mg.Spec.ForProvider.VPCConfig[i3].SubnetIds: referenced field was empty (referenced resource may not yet be ready)
    Reason:                ReconcileError
    Status:                False
    Type:                  Synced
Events:
  Type     Reason                           Age                From                                              Message
  ----     ------                           ----               ----                                              -------
  Warning  CannotResolveResourceReferences  12m (x3 over 12m)  managed/eks.aws.upbound.io/v1beta1, kind=cluster  cannot resolve references: mg.Spec.ForProvider.RoleArn: referenced field was empty (referenced resource may not yet be ready)
  Warning  CannotResolveResourceReferences  11m (x3 over 12m)  managed/eks.aws.upbound.io/v1beta1, kind=cluster  cannot resolve references: mg.Spec.ForProvider.VPCConfig[i3].SubnetIds: referenced field was empty (referenced resource may not yet be ready)
```

```
kubectl get subnets
NAME                                READY   SYNCED   EXTERNAL-NAME              AGE
platform-ref-aws-cnoe-nm9pn-89k8b   True    True     subnet-0b286a046b6931ea6   13m
platform-ref-aws-cnoe-nm9pn-n8n2q   True    True     subnet-0a9814ca1268efc19   13m
platform-ref-aws-cnoe-nm9pn-nrj7g   True    True     subnet-070abff05f30d8712   13m
platform-ref-aws-cnoe-nm9pn-xqsd6   True    True     subnet-0caaa3fb58c03fe6f   13m
```

```
apiVersion: v1
items:
- apiVersion: ec2.aws.upbound.io/v1beta1
  kind: Subnet
  metadata:
    annotations:
      crossplane.io/composition-resource-name: subnetPublicB
      crossplane.io/external-create-pending: "2023-11-18T14:36:40Z"
      crossplane.io/external-create-succeeded: "2023-11-18T14:36:40Z"
      crossplane.io/external-name: subnet-0b286a046b6931ea6
      upjet.upbound.io/test: "true"
    creationTimestamp: "2023-11-18T14:36:14Z"
    finalizers:
    - finalizer.managedresource.crossplane.io
    generateName: platform-ref-aws-cnoe-nm9pn-
    generation: 4
    labels:
      access: public
      crossplane.io/claim-name: platform-ref-aws-cnoe
      crossplane.io/claim-namespace: default
      crossplane.io/composite: platform-ref-aws-cnoe-nm9pn
      networks.aws.platform.upbound.io/network-id: platform-ref-aws-cnoe
      zone: us-west-2b
[...]
```

### What environment did it happen in?

* Crossplane Version:
* Provider Version:
* Kubernetes Version:  
* Kubernetes Distribution:

**Comment by haarchri** [comment] 2023-11-18 15:08
after a while we will see:

```
Events:
  Type     Reason                         Age   From                                              Message
  ----     ------                         ----  ----                                              -------
  Warning  CannotObserveExternalResource  31s   managed/eks.aws.upbound.io/v1beta1, kind=cluster  failed to observe the resource: [{0 reading EKS Cluster (platform-ref-aws-cnoe-nm9pn-9l46l): RequestCanceled: request context canceled
caused by: context canceled  []}]
```

**Comment by haarchri** [comment] 2023-11-18 16:34
can see the same issue with v0.43.0 - perhaps its an problem with composition functions patch&transform - see with v0.43.0 every second a flip:

```
Vpc Config:
   Endpoint Private Access: true
   Endpoint Public Access:  true
   Subnet Id Refs:
    Name: platform-ref-aws-cnoe-66c8s-vldn9
    Name: platform-ref-aws-cnoe-66c8s-xtggc
   Subnet Id Selector:
    Match Labels:
     Access:                    public
     networks.aws.platform.upbound.io/network-id: platform-ref-aws-cnoe
   Subnet Ids:
    subnet-0d3ae81fc5a1a439b
    subnet-080d0fdea79012923
```

and 

```
Vpc Config:
   Endpoint Private Access: true
   Endpoint Public Access:  true
   Subnet Id Selector:
    Match Labels:
     Access:                    public
     networks.aws.platform.upbound.io/network-id: platform-ref-aws-cnoe
```

**Comment by haarchri** [comment] 2023-11-18 18:28
okay looks like a generic problem with crossplane v.1.14 with v1.13 embedded patch & transform its working

**Comment by haarchri** [comment] 2023-11-18 18:28
feels like a problem with arrays and ref / selectors

**Comment by sttts** [comment] 2023-11-18 20:05
Array are replaced, never merged by default. SSA has `list-type: map`. But for that it needs a key, which `vpcConfig` does not have. Hence, it is not surprising that Crossplane overwrites the array value created by the provider.

**Comment by mbbush** [comment] 2023-11-19 04:46
@haarchi Does it work on 1.14 with a "old" style composition (with a resources block, not referencing the patch-and-transform composition function)? My understanding was that in that case crossplane still used client-side apply, although I could be wrong.

**Comment by haarchri** [comment] 2023-11-19 06:31
The issue arises with the old style in version 1.14, where the function is not present. In version 1.13, everything is "working" correctly; subnetIds are resolved, the managed resource is created, and during creation, the subnetIds are not visible like 1.14. However, after the resource is ready, the subnetIds are late-initialized. This suggests that in version 1.13, it appears to be "working" possibly due to Crossplane not being fast enough in version 1.14. ?!

**Comment by ulucinar** [comment] 2023-11-28 17:28
The root cause of this issue is https://github.com/crossplane/crossplane/issues/3335. As explained in detail there, the MR reconciler and the XR reconciler race on updating the list (`spec.forProvider.vpcConfig`) item:
- The XR reconciler updates the label selector for the subnet IDs (`spec.forProvider.vpcConfig[0].subnetIdSelector`
- The MR reconciler updates `spec.forProvider.vpcConfig[0].subnetIds` with the resolved references
- The list item `spec.forProvider.vpcConfig[0]` is updated atomically. The MR reconciler preserves the label selector and thus what's observed is that the resolved subnet IDs appear and disappear.

Crossplane v1.14's XR reconciler reconciles more frequently when the XR is not ready and the problem is much more visible with Crossplane v1.14.

**Comment by sterziev88** [comment] 2023-12-04 11:02
Hello guys, 

Sorry I know that my question in not related to the issue but I saw that is seems you are using eks created by crossplane so I wanted to ask you how you managed to update aws-auth configmap during creation of the cluster? What I mean:
I create EKS with crossplane provider role and after that I can't access any of the resources and I am not able to update the aws-auth because only the role created the EKS has this permission. Unfortunately I can't assume this role... so the only way is update the aws-auth during creation of the cluster... Maybe I miss something. 

Thank you in advance for any help :)

**Closed** 2023-12-28 11:33 UTC
Labels: bug
