### ISSUE TITLE
facing this error while  CannotConnectToProvider  with localstack and crossplane 

### ISSUE THREAD

**Issue by Shubhambawa98** [upbound/provider-aws#607] opened 2023-03-15 11:56 UTC
What happened?

Warning  CannotConnectToProvider          94s (x135 over 6m13s)  managed/s3.aws.upbound.io/v1beta1, kind=bucket  (combined from similar events): cannot get terraform setup: cannot get the caller identity: GetCallerIdentity query failed: GetCallerIdentity query failed: operation error STS: GetCallerIdentity, https response error StatusCode: 403, RequestID: 49c697b9-4ef8-4a9d-82e4-eace2e2815b2, api error InvalidClientTokenId: The

 Here you can find my providerConfig.yml below 

apiVersion: aws.upbound.io/v2beta1
kind: ProviderConfig
metadata:
  name: localstack
spec:
  endpoint:
    hostnameImmutable: false
    url:
      type: Static
      static: http://192.168.126.129:31566/
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: test
      key: creds

Help us to reproduce your bug as succinctly and precisely as possible. Artifacts
such as example manifests or a script that triggers the issue are highly
appreciated!

**Comment by ytsarev** [comment] 2023-03-16 16:44
Looks like a duplicate of https://github.com/upbound/provider-aws/issues/206 . We already have PR for it https://github.com/upbound/provider-aws/pull/447 under review. I will close this one as duplicate, please reopen if required.

**Closed by ytsarev** 2023-03-16 16:44 UTC
Labels: bug, community
