### ISSUE TITLE
v0.44.0 - [controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.

### ISSUE THREAD

**Issue by haarchri** [upbound/provider-aws#973] opened 2023-11-18 14:46 UTC
### What happened?

see the following error when running v0.44.0 provider version:

```
kubectl logs -n upbound-system       upbound-provider-aws-eks-cbf3f930b3cf-7d5f5cc6b5-vlc6s
{"level":"info","ts":"2023-11-18T14:35:17Z","logger":"provider-aws","msg":"Beta feature enabled","flag":"EnableBetaManagementPolicies"}
[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.
Detected at:
	>  goroutine 4189 [running]:
	>  runtime/debug.Stack()
	>  	runtime/debug/stack.go:24 +0x64
	>  sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
	>  	sigs.k8s.io/controller-runtime@v0.16.3/pkg/log/log.go:60 +0xf4
	>  sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).WithValues(0x400c13f680, {0x400ce74700, 0x4, 0x4})
	>  	sigs.k8s.io/controller-runtime@v0.16.3/pkg/log/deleg.go:168 +0x3c
	>  github.com/go-logr/logr.Logger.WithValues(...)
	>  	github.com/go-logr/logr@v1.2.4/logr.go:323
	>  sigs.k8s.io/controller-runtime/pkg/builder.(*Builder).doController.func1(0x4003db2660)
	>  	sigs.k8s.io/controller-runtime@v0.16.3/pkg/builder/controller.go:402 +0x278
	>  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0x400b869040, {0x1125a450, 0x40002cfef0}, {0xdfbd3a0?, 0x4003db2640?})
	>  	sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:306 +0x138
	>  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0x400b869040, {0x1125a450, 0x40002cfef0})
	>  	sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266 +0x1a0
	>  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	>  	sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227 +0x74
	>  created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	>  	sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:223 +0x43c
```

### What environment did it happen in?

* Crossplane Version:
* Provider Version:
* Kubernetes Version:  
* Kubernetes Distribution:

**Comment by stevendborrelli** [comment] 2023-11-18 15:12
Maybe related to https://github.com/crossplane/crossplane/pull/4403?

**Comment by turkenh** [comment] 2023-12-06 20:34
Duplicate of https://github.com/upbound/provider-aws/issues/854

**Closed by turkenh** 2023-12-06 20:34 UTC
Labels: bug, needs:triage
